# Generated by Django 2.2.16 on 2022-01-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220123_1100'),
        ('users', '0003_auto_20220119_2055'),
    ]

    operations = [
    ]
