# Generated by Django 2.2.16 on 2022-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
