# Generated by Django 2.2.16 on 2022-01-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20220123_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
    ]
