# Generated by Django 2.2.16 on 2022-01-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_remove_title_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='titles.Category')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title')),
            ],
        ),
    ]
