# Generated by Django 2.2.16 on 2022-01-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_titlecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='titles.Genre'),
        ),
        migrations.DeleteModel(
            name='TitleCategory',
        ),
    ]
