# Generated by Django 2.2.16 on 2022-01-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_auto_20220125_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
