# Generated by Django 2.2.16 on 2022-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_auto_20220125_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='titles.Genre'),
        ),
    ]
